### ISSUE TITLE
CSV download for entire dataset somewhere 

### ISSUE THREAD

**Issue by gbp** [mysociety/stop-and-search#20]
Similar to #19 use Datasette

**Comment by garethrees** [comment]
Need to find a place to display this. Maybe on the homepage, or in the footer? Maybe like [CAPE](https://cape.mysociety.org/):

![Screenshot 2023-08-07 at 15 24 16](https://github.com/mysociety/stop-and-search/assets/282788/f83fae00-cd7b-4033-8a84-99f2f64eddf6)
