### ISSUE TITLE
Data Protection Impact Assessment (DPIA)

### ISSUE THREAD

**Issue by garethrees** [mysociety/stop-and-search#4]
We should consider a [DPIA](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/) for our processing of the source data of this project.

I don't know yet how we'll be processing the extracted data, and we're confident that by the time mySociety handles it it should be sufficiently anonymised such that there's no likelihood of us processing any personal information, but that's what a DPIA is there to confirm.

As we'll only be a data processor (rather than data controller) for this project for a relatively short period of time, In the first instance it would be worth knowing if Black Thrive have done a DPIA around the work on generating the source data that this project will use.

**Comment by garethrees** [comment]
Black Thrive will take the lead on this. We'll review and contribute any thoughts once they've made a first pass. I'm happy to keep an eye on this until it comes to review, at which point I'll probably need to hand off to @sagepe.

**Comment by garethrees** [comment]
We've now got a [draft to review]( https://groups.google.com/a/mysociety.org/g/alaveteli/c/oWmGIQuIB3I/m/faHLvW7-BAAJ), so assigning @sagepe.

**Comment by sagepe** [comment]
I've put a copy of the Word document attached to that thread in the relevant Drive folder: https://docs.google.com/document/d/1mZErEk4LyCmsXpbPG66Z8e6V_YLlq3m0/edit

**Comment by sagepe** [comment]
I've left some comments on the document.

From what I can see, the processing is low risk. Although the data being processed includes sensitive elements, we are only processing data already provided publicly by the Police that has already been through [a process of anonymisation](https://data.police.uk/about/#stop-search). There should be nothing in the data that could lead to the unambiguous identification of any specific person. The data that will be used is licensed under the [Open Government License 3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), which includes specific permission to "copy, publish, distribute and transmit the Information", so outlining our own justification for processing the data on this basis seems to be going above and beyond, but no harm in doing so.

**Comment by garethrees** [comment]
We're happy with this as a data processor.
